CREATE TABLE FITNESS_DATA.PROD_HOURLY_SUMMARY 
    ( 
     ID              NUMBER , 
     ACTIVITY_HOUR   TIMESTAMP , 
     CALORIES_BURNED NUMBER ,
     TOTAL_INTENSITY   NUMBER , 
     AVERAGE_INTENSITY NUMBER ,
     STEP_TOTAL    NUMBER      
    ) 
    TABLESPACE DATA 
    LOGGING 
;