CREATE TABLE FITNESS_DATA.STG_DAILYACTIVITY_MERGED 
    ( 
     ID                                   NUMBER , 
     ACTIVITY_DATE                        DATE , 
     TOTAL_STEPS                          NUMBER , 
     TOTAL_DISTANCE_KILOMETER             NUMBER , 
     TRACKER_DISTANCE_KILOMETER           NUMBER , 
     LOGGED_ACTIVITIES_DISTANCE_KILOMETER NUMBER , 
     VERYACTIVE_DISTANCE_KILOMETER        NUMBER , 
     MODERATELYACTIVE_DISTANCE_KILOMETER  NUMBER , 
     LIGHTACTIVE_DISTANCE_KILOMETER       NUMBER , 
     SEDENTARYACTIVE_DISTANCE_KILOMETER   NUMBER , 
     VERYACTIVE_MINUTES                   NUMBER , 
     FAIRLYACTIVE_MINUTES                 NUMBER , 
     LIGHTLYACTIVE_MINUTES                NUMBER , 
     SEDENTARY_MINUTES                    NUMBER , 
     CALORIES_BURNED                      NUMBER 
    ) 
    TABLESPACE DATA 
    LOGGING 
;