CREATE TABLE FITNESS_DATA.STG_MINUTECALORIESNARROW_MERGED 
    ( 
     ID             NUMBER , 
     ACTIVITY_MINUTE TIMESTAMP , 
     CALORIES_BURNED       NUMBER 
    ) 
    TABLESPACE DATA 
    LOGGING 
;