CREATE TABLE FITNESS_DATA.STG_MINUTESLEEP_MERGED
    ( 
     ID     NUMBER , 
     MEASUREMENT_DATE TIMESTAMP , 
     SLEEP_STATE  NUMBER , 
     LOGID  NUMBER 
    ) 
    TABLESPACE DATA 
    LOGGING 
;