CREATE TABLE FITNESS_DATA.STG_HOURLYINTENSITIES_MERGED 
    ( 
     ID               NUMBER , 
     ACTIVITY_HOUR     TIMESTAMP , 
     TOTAL_INTENSITY   NUMBER , 
     AVERAGE_INTENSITY NUMBER 
    ) 
    TABLESPACE DATA 
    LOGGING 
;