CREATE TABLE FITNESS_DATA.STG_DAILYSLEEP_MERGED 
    ( 
     ID                 NUMBER , 
     SLEEP_DATE           DATE , 
     TOTAL_SLEEP_RECORDS  NUMBER , 
     TOTAL_MINUTES_ASLEEP NUMBER , 
     TOTAL_TIME_IN_BED     NUMBER 
    ) 
    TABLESPACE DATA 
    LOGGING 
;