CREATE TABLE FITNESS_DATA.STG_MINUTEINTENSITIESNARROW_MERGED 
    ( 
     ID             NUMBER , 
     ACTIVITY_MINUTE TIMESTAMP , 
     INTENSITY      NUMBER 
    ) 
    TABLESPACE DATA 
    LOGGING 
;